services:
  api:
    build: .
    command: uvicorn src.run:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - "8003:8000"

  streamlit:
    build: .
    command: streamlit run story_creator.py --server.port=8501
    volumes:
      - .:/code
    ports:
      - "8503:8501"
